version: "3.0"

services:
  news:
    build: .
    image: tech_news_image
    container_name: tech_news
    tty: true # docker run -t
    stdin_open: true # docker run -i
    command: bash
    restart: unless-stopped
    depends_on:
      - mongodb
    environment:
      - DB_HOST=mongodb
      - DB_PORT=27017
    networks:
      - tech_news_net

  mongodb:
    image: mongo:4.4.14
    container_name: tech_news_db
    restart: unless-stopped
    networks:
      - tech_news_net

networks:
  tech_news_net:
    driver: bridge
